INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Evils Dungarees', 'clothing', 50, 50);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Conserve', 'sneakers', 45, 10);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('The Misadventures of Marc and Pat', 'movies', 20, 500);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Sanaponic radio', 'electronics', 17, 80);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Reddy Tuxpin', 'toys', 80, 5);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Ennui', 'fragrances', 60, 8);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Angst', 'fragrances', 100, 14);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Los Hipopotmos Hambrientos', 'toys', 28, 36);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('Shnirt', 'clothing', 25, 700);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ('The Horse Whisperer 2: The Revenge of Marc and Pat', 'movies', 250, 3);